#!/usr/bin/env python3
"""
自动生成的执行器 skill
Generated by Skills Factory — 基于真实执行记录
目标: 系统自愈能力测试工作流
"""
import sys
import json
import time

sys.path.insert(0, '/opt/data')

from organs.auto_healing import check_all, auto_fix, verify_fix
from organs.unified_push import push_error, push_warning
from organs.intent_engine import parse_intent, execute_intent

SKILL_META = {
    "goal": "系统自愈能力测试工作流",
    "task_types": ["analysis", "healing", "push"],
    "task_count": 3,
    "descriptions": ["分析系统健康状态", "执行自愈检查", "推送结果通知"],
}

def execute(params: dict = None) -> dict:
    """
    执行此skill的主函数
    
    参数:
        params: 执行参数（从工作流传入）
    
    返回:
        结果字典
    """
    params = params or {}
    results = []
    
    # === 执行步骤 ===
    # 以下代码基于真实执行记录自动生成
    # 每个步骤对应一次真实的任务执行
    
    for i, analysis in enumerate(["analysis", "healing", "push"]):
        step_result = {
            "step": i + 1,
            "task_type": analysis,
            "status": "pending",
            "started_at": time.time(),
        }
        
        # 根据任务类型调用对应器官
        if analysis == "analysis":
            # 分析任务：使用intent_engine
            from organs.intent_engine import parse_intent
            result = parse_intent(params.get("query", "系统自愈能力测试工作流"))
            step_result["result"] = result
            step_result["status"] = "completed"
            
        elif analysis == "execution":
            # 执行任务：使用workflow_engine
            from organs.workflow_engine import create_workflow, dispatch_next, update_task_result
            tasks = params.get("tasks", [])
            wf_id = create_workflow("系统自愈能力测试工作流", tasks)
            step_result["workflow_id"] = wf_id
            step_result["status"] = "completed"
            
        elif analysis == "healing":
            # 自愈任务：使用auto_healing
            from organs.auto_healing import check_all, auto_fix, verify_fix
            health = check_all()
            failed = [h for h in health if not h["healthy"]]
            if failed:
                for h in failed:
                    fix = auto_fix(h["rule_id"])
                time.sleep(2)
                health2 = check_all()
                step_result["still_failed"] = [h["rule_id"] for h in health2 if not h["healthy"]]
            step_result["status"] = "completed"
            step_result["health"] = health
            
        elif analysis == "push":
            # 推送任务：使用unified_push
            from organs.unified_push import push_success, push_error
            push_success("Skill执行完成", "{goal_escaped}")
            step_result["status"] = "completed"
            
        elif analysis == "learning":
            from organs.learning_loop import on_workflow_complete
            wf_id = step_result.get("workflow_id")
            if wf_id:
                report = on_workflow_complete(wf_id)
                step_result["learning_report"] = report
            step_result["status"] = "completed"
            
        else:
            step_result["status"] = "skipped"
            step_result["note"] = f"未识别任务类型: {analysis}"
        
        step_result["elapsed"] = time.time() - step_result["started_at"]
        results.append(step_result)
    
    return {
        "skill_name": "系统自愈能力测试工作流",
        "meta": SKILL_META,
        "steps": results,
        "total_steps": len(results),
        "completed": sum(1 for r in results if r["status"] == "completed"),
    }


if __name__ == "__main__":
    # CLI测试入口
    result = execute()
    print(json.dumps(result, ensure_ascii=False, indent=2))
